service: romcal-api

plugins:
  - serverless-offline

package:
  exclude:
    - .git/**
    - .idea/**
    - src/**
    - test/**
    - coverage/**
    - .*
    - nest-cli.json
    - README.md
    - tsconfig.*
  include:
    - dist/*.js
    - dist/*.js.map
    - dist/**/*.js
    - dist/**/*.js.map

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  memory: 128
  apiGateway:
    minimumCompressionSize: 1024 # Enable gzip compression for responses > 1 KB
  environment:
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1

functions:
  app:
    handler: dist/src/lambda.handler
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'
